### PR TITLE
Registered AS142280

### PR DESCRIPTION
**Pull request by NaiveTomcat**

### CODE REVIEW

**Comment by NaiveTomcat** [comment]
Verification for ownership of Internet ASN AS142280:

Whois information of AS142280:
```
$ whois -h whois.apnic.net AS142280
% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

% Information related to 'AS141626 - AS142649'

as-block:       AS141626 - AS142649
descr:          APNIC ASN block
remarks:        These AS numbers are further assigned by APNIC
remarks:        to APNIC members and end-users in the APNIC region
admin-c:        HM20-AP
tech-c:         HM20-AP
mnt-by:         APNIC-HM
mnt-lower:      APNIC-HM
last-modified:  2020-10-21T04:09:48Z
source:         APNIC

role:           APNIC Hostmaster
address:        6 Cordelia Street
address:        South Brisbane
address:        QLD 4101
country:        AU
phone:          +61 7 3858 3100
fax-no:         +61 7 3858 3199
e-mail:         helpdesk@apnic.net
admin-c:        AMS11-AP
tech-c:         AH256-AP
nic-hdl:        HM20-AP
remarks:        Administrator for APNIC
notify:         hostmaster@apnic.net
mnt-by:         MAINT-APNIC-AP
last-modified:  2013-10-23T04:06:51Z
source:         APNIC

% Information related to 'AS142280'

% Abuse contact for 'AS142280' is 'abuse@naivetomcat.cn'

aut-num:        AS142280
as-name:        NTEREN-BACKBONE
descr:          NaiveTomcat Education and Research Experimental Network Backbone
country:        CN
org:            ORG-WLNT1-AP
admin-c:        YD991-AP
tech-c:         YD991-AP
abuse-c:        AN2919-AP
mnt-routes:     MAINT-LSHIY-CN
mnt-by:         APNIC-HM
mnt-irt:        IRT-NAIVETOMCAT-CN
last-modified:  2021-05-20T01:11:25Z
source:         APNIC

irt:            IRT-NAIVETOMCAT-CN
address:        Xi'an Jiaotong University, Xianning Rd, Beilin District, Xi'an, Shaanxi, China
e-mail:         noc@naivetomcat.cn
abuse-mailbox:  abuse@naivetomcat.cn
admin-c:        YD991-AP
tech-c:         YD991-AP
auth:           # Filtered
remarks:        noc@naivetomcat.cn was validated on 2021-07-19
remarks:        abuse@naivetomcat.cn was validated on 2021-07-19
mnt-by:         MAINT-LSHIY-CN
last-modified:  2021-07-19T08:03:26Z
source:         APNIC

organisation:   ORG-WLNT1-AP
org-name:       LSHIY Network Technology Limited
country:        CN
address:        LSHIY Group, No. 333 Jianshe Avenue, Jianghan District
phone:          +86-27-59762459
fax-no:         +86-27-59762459
e-mail:         noc@lshiy.com
mnt-ref:        APNIC-HM
mnt-by:         APNIC-HM
last-modified:  2021-04-22T12:57:48Z
source:         APNIC

role:           ABUSE NAIVETOMCATCN
address:        Xi'an Jiaotong University, Xianning Rd, Beilin District, Xi'an, Shaanxi, China
country:        ZZ
phone:          +000000000
e-mail:         noc@naivetomcat.cn
admin-c:        YD991-AP
tech-c:         YD991-AP
nic-hdl:        AN2919-AP
remarks:        Generated from irt object IRT-NAIVETOMCAT-CN
abuse-mailbox:  abuse@naivetomcat.cn
mnt-by:         APNIC-ABUSE
last-modified:  2021-05-20T01:11:25Z
source:         APNIC

person:         Yitong Dang
address:        Xi'an Jiaotong University, Xianning Rd, Beilin District, Xi'an, Shaanxi, China
country:        CN
phone:          +86-17782596129
e-mail:         tomdang@naivetomcat.cn
nic-hdl:        YD991-AP
mnt-by:         MAINT-LSHIY-CN
last-modified:  2021-05-17T04:22:57Z
source:         APNIC

% This query was served by the APNIC Whois Service version 1.88.15-SNAPSHOT (WHOIS-US3)
```

The email associated with this GitHub account is tomdang@naivetomcat.cn as the email associated with the admin-c of the ASN. You can send emails to any of the three emails in the whois query to validate.

**Comment by steveyiyo** [comment]
@NaiveTomcat I have sent a validation email, please check it.

**Comment by NaiveTomcat** [comment]
> @NaiveTomcat I have sent a validation email, please check it.

Replied. The sender is not the abuse mailbox since the abuse mailbox is set to be a forwarder.

**Comment by steveyiyo** [comment]
Approved.

**Comment by NaiveTomcat** [comment]
Is it needed to change the `valid` option in asn/AS142280?

**Pull request merged**
